Main post killer feature
abnormalize0/DailyTeleFrog pull request #138
Opened 2024-03-18 22:37 UTC by waverew

As for now component is being rendered in App.vue

2024-03-20 23:08 UTC, serynabatov requested changes

2024-03-20 23:08 UTC, serynabatov commented on client/src/components/post/AvatarSection/AvatarSection.html
To have a better composition you can insert all these files into one file ".vue" 

Let's make an example. `AvatarSection.vue`

```
<template>
HTML file goes here
</template>

<style>
CSS file goes here
</style>

<script>
component logic goes here
</script>
```
You can leave the test files though I can not see any changes on the packages.json regarding them.
So I'd assume we need to remove them too and when we will have a real script functionality use a jest library.

Also when you will remove these files you won't need the folders! So components/post will be enough to contain only 5 files about the post

2024-03-20 23:08 UTC, serynabatov commented on client/src/components/post/AvatarSection/AvatarSection.html
> +      asdasd
What is asdasd???

2024-03-20 23:08 UTC, serynabatov commented on client/src/components/post/MainPost/MainPost.js
Same as above

2024-03-20 23:08 UTC, serynabatov commented on client/src/components/post/MainPost/MainPost.js
> +    header: String,
Let's rename variables for header and body to postHeader and bodyHeader
Also the same for img -> imgHeader

It is for the compatibility issues

2024-03-20 23:08 UTC, serynabatov commented on client/src/components/post/MainPost/MainPost.scss
> +p {
Why are you using tag p?

There is a special class for it

2024-03-20 23:08 UTC, serynabatov commented on client/src/components/post/PostFooter/PostFooter.html
Same as above

2024-03-20 23:08 UTC, serynabatov commented on client/src/components/post/PostFooter/PostFooter.js
> +    hashtags: Array,
Instead of 

```
hashTags: Array
```

use
```
hashtags: []
```


While using "Array" name there could be clashes with some libraries

2024-03-20 23:08 UTC, serynabatov commented on client/src/components/post/PostHashtag/PostHashtag.html
Same as above

2024-04-06 09:25 UTC, waverew commented
checked everything, fixed hashtags. Looks like good to go

2024-04-07 18:37 UTC, merged