#119 editor remake
abnormalize0/DailyTeleFrog pull request #141
Opened 2024-04-08 20:27 UTC by abnormalize0

Большой ремейк редактора. @serynabatov 
Переписал на vue-стиль, по возможности стал использовать готовые решения вместо самописных, внес несколько QoL фич (указатель текущего положения на миникарте, возможность быстрого перехода к конкретным блокам). Из критического функционала пока что нет функции опубликовать пост. Кроме того в данный момент редактор почему-то вызывает ошибку cannot read properties of null (reading 'parentnode').

2024-04-14 12:40 UTC, serynabatov requested changes
Очень много надо переделать, часть из того что ты написал не взлетит на проде (Я объяснил почему)

Я пока еще не смотрел полностью логику, потому что PR очень большой, а я оч маленький
А если без шуток, очень тяжело понимать логику, когда в PR находится очень много лишних элементов

Исправь, потом посмотрим еще раз

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        document.getElementById("top_insert" + id).style.visibility = "hidden";
Никких document.getElementById не должно присутствовать!

Вью - реактивный фреймворк! То что ты делаешь тут ломает саму парадигму использования вью (помимо того, что это может работать некорректно при разных версиях)

Чтобы сделать то, что ты хочешь обычно следует использовать сам template 

https://stackoverflow.com/questions/59384530/how-to-toggle-visibility-of-vuejs-component

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        document.getElementById("bot_insert" + id).style.visibility = "hidden";
Поищи мой комментарий про document.getElementById

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        document.getElementById("bot_insert" + id).style.visibility = "visible";
Поищи мой комментарий про document.getElementById

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        document.getElementById("top_insert" + id).style.visibility = "visible";
Поищи мой комментарий про document.getElementById

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        let modal = document.getElementById("modal_menu");
Поищи мой комментарий про document.getElementById

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        let modal = document.getElementById("modal_menu");
Переписывай эту логику полностью, никаких изменений в самом джаваскрипте у стилей присутствовать не может и не должно 
Это должен открываться или отдельный компонент или реактивный класс

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +          image: document.getElementById("new_img").value
Поищи мой комментарий про document.getElementById

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +          alert("Должна быть хотя бы одна картинка");
alert - это плохо 

Никогда не используй алерты, хочешь вывести ошибку, выведи ошибку формы
Эта ссылка с точки зрения юзабилити
https://www.quora.com/Why-is-JavaScripts-alert-box-considered-a-bad-design-from-usability-point-of-view

А вторая причина в том что алерт блокирует джаваскрипт выполнение, это может оч вкусно поломать нам весь фреймворк, убирай

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        this.slidesarray[this.current_image][index].title = document.getElementById("img_title" + index).value;
Поищи мой комментарий про document.getElementById

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        document.getElementById("modal_image_insert").style.display = "none";
Поищи мой комментарий про document.getElementById

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        let modal = document.getElementById("modal_image_insert");
Поищи мой комментарий про document.getElementById

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        let pos = document.getElementById("position")
Поищи мой комментарий про document.getElementById

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +          setTimeout(function() { that.recursive_shutdown() }, 50);
Никаких сет таймаутов
https://stackoverflow.com/questions/38399050/vue-equivalent-of-settimeout

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        setTimeout(function() { pos.style.visibility = "hidden"; }, 200)
Поищи мой комментарий про setTimeout

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        let pos = document.getElementById("position")
Поищи мой комментарий про document.getElementById

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        setTimeout(function() { content.classList.toggle("blink"); }, 300)
Поищи мой комментарий про setTimeout

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        setTimeout(function() { content.classList.toggle("blink"); }, 800)
Поищи мой комментарий про settimeout

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        console.log(toRaw(this.myContent[id]))
Убери все console.log из прода

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        console.log(toRaw(this.myContent[id]))
Я это не откомментил везде, но этого быть не должно в мерже

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        document.getElementById("modal_menu").style.display = "none";
Поищи мой комментарий про document.getElementById

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        this.blocks.splice(this.blocks.map(function (img) { return img.id; }).indexOf(this.after_block) + this.block_place, 0, {name:'Element ' + this.last_id, id: this.last_id, type: type})
Давай так 
Ты очистишь код, а потом я скажу как эту функцию сделать лучше, этого быть не должно
Но мне кажется, как ты почистишь код, эта проблема уйдет сама собой

Оставлю здесь только просьбу использовать arrow functions, которые де факто стандарт

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +      document.getElementById("position").style.height = document.getElementById("worksheet").clientHeight * this.scale + "px"
Поищи мой комментарий про document.getElementById

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        let content = document.getElementById("block_element" + block.id)
Поищи мой комментарий про document.getElementById

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        let element = document.getElementById("miniature" + block.id)
Поищи мой комментарий про document.getElementById

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        let item = document.getElementById("miniature_item" + block.id)
Поищи мой комментарий про document.getElementById

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        current_image: -1,
Я думаю после рефактора ты сможешь удалить очень много ненужных переменных, такие как scale и last_id как минимум

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +    <div class="position" id="position"></div>
Тут клэш имени класса и айди, я удивлен, что vue тебе это компилирует, поменяй

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +  <div class="right_menu">
Поищи мой комментарий про CSS названия классов

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +          class="miniature_item"
Поищи мой комментарий про CSS названия классов

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +          <div class="insert_button" :id="`top_insert` + block.id" @click="open_add_menu($event, block.id); block_place = 0"></div>
Поищи мой комментарий про CSS названия классов

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +          <div class="insert_button" :id="`bot_insert` + block.id" @click="open_add_menu($event, block.id); block_place = 1"></div>
Поищи мой комментарий про CSS названия классов

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +      <div class="single_block">
Поищи мой комментарий про CSS названия классов

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +    <div class="modal_back">
Поищи мой комментарий про CSS названия классов

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +      <draggable v-model="slidesarray[current_image]"  handle=".handle" @dragstart="drag_start_handler">
Я не вижу .handle - полагаю, что этого и нет вообще, удали если не используется

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +          <div class="modal_grid">
Поищи мой комментарий про CSS названия классов

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +            <input :id="`img_title` + index" @input="image_title(index)" size="10" :value=block.title />
Поищи мой комментарий про CSS названия классов (применимо и для айди)

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +            <div style="font-size: 40px; color:black;" @click="delete_img(index)">&times;</div>
Все стили которые больше одного свойства должны быть вынесены в класс

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        <div class="modal_grid">
Поищи мой комментарий про CSS названия классов

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +          <input id="new_img" size="10" placeholder="Укажите URL" />
Поищи мой комментарий про CSS названия классов (применимо и для айди)

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +          <div style="font-size: 40px; color:black;" @click="add_img()">&or;</div>
Поищи мой комментарий про стили в HTML коде

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +    <div @click="add_element('text')" class="block_type" >Текстовый блок</div>
Поищи мой комментарий про CSS названия классов

2024-04-14 12:40 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +    <div @click="add_element('carousel')" class="block_type">Карусель изображений</div>
Поищи мой комментарий про CSS названия классов

2024-04-14 12:40 UTC, serynabatov commented on client/public/css/NewPostStyle.css
Весь этот файл должен перелезть внутрь NewPostView.vue объект, чтобы было меньше зависимостей, а также чтобы это было читаемо

2024-04-14 12:40 UTC, serynabatov commented on client/public/css/NewPostStyle.css
> +    z-index: 100;
Не используй z-index вообще 

Честно говоря при рефакторе, я и лемас потратили кучу времени, чтобы придумать как все сделать без зед индексов, поскольку наличие зед индексов при увеличении проекта создает такое большое кол-во проблем при верстке, что лучше их избежать

2024-04-14 12:40 UTC, serynabatov commented on client/public/css/NewPostStyle.css
> +    z-index: 100;
Тот же комментарий про зед индекс
Лучше избегать, если прям совсем не можешь, тогда использовать

2024-04-14 12:40 UTC, serynabatov commented on client/public/css/NewPostStyle.css
> +    font-size: 1.2em;
Ты везде используешь пиксели, а тут em 
Используй везде пиксели

Скажу больше у тебя этот класс не используется вообще

Если бы этот файл был бы в том же файле что и NewPostView.vue 
Найти неиспользуемые параметры было бы легче

2024-04-14 12:40 UTC, serynabatov commented on client/public/css/NewPostStyle.css
> +    width: 50vw;
Думай с вьюпортами, опять же ты используешь везде пиксели, а тут почему-то вьюпорты, подумай как это избежать

2024-04-14 12:40 UTC, serynabatov commented on client/src/App.vue
> +    <router-view/>
Пометь это в коде, что это только для твоего теста, чтобы я с лемасом потом  не мучались при создании авторизации

2024-04-14 12:40 UTC, serynabatov commented on client/src/App.vue
> +    <router-view/>
Можем придумать какой-то хэштег 
Типа IDEA или т.д.
На твое усмотрение

2024-04-14 12:43 UTC, abnormalize0 commented on client/public/css/NewPostStyle.css
> +    font-size: 1.2em;
Это внутренний класс библиотеки vueperslide, так что на самом деле используется

2024-04-14 13:07 UTC, serynabatov commented on client/public/css/NewPostStyle.css
> +    font-size: 1.2em;
А почему ты его должен прописывать
Ты типа переопределяешь font-size?

2024-04-18 19:35 UTC, abnormalize0 commented on client/public/css/NewPostStyle.css
> +    z-index: 100;
С модальным окном мне кажется иначе никак, а в остальном да, постараюсь избавиться.

2024-04-18 19:35 UTC, abnormalize0 commented on client/public/css/NewPostStyle.css
> +    font-size: 1.2em;
Чтоб настраивать внешний вид подписи к изображению

2024-04-18 19:50 UTC, abnormalize0 commented on client/src/views/NewPostView.vue
> +      <draggable v-model="slidesarray[current_image]"  handle=".handle" @dragstart="drag_start_handler">
Это указание что драгндроп работает только на объекты класса handle, надо потому что я перетаскиваю сущность в которой есть текстовое поле, и если я не оставлю такое указание то им невозможно будет пользоваться

2024-04-20 16:32 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +      <draggable v-model="slidesarray[current_image]"  handle=".handle" @dragstart="drag_start_handler">
@abnormalize0 а можешь ссылку на документацию дать?
Это очень странное использование)

2024-04-20 16:33 UTC, serynabatov commented on client/public/css/NewPostStyle.css
> +    z-index: 100;
@abnormalize0 
Попробуй воспользоваться модальным окном, которое уже предоставляет vuetify 
https://vuetifyjs.com/en/components/dialogs/

2024-04-20 16:34 UTC, serynabatov commented on client/public/css/NewPostStyle.css
> +    font-size: 1.2em;
@abnormalize0 
А можешь скинуть документацию?
Мне кажется можно симпатичнее сделать, чтобы мы голову потом не ломали

2024-04-20 16:52 UTC, abnormalize0 commented on client/public/css/NewPostStyle.css
> +    font-size: 1.2em;
https://antoniandre.github.io/vueper-slides/

2024-04-20 16:54 UTC, abnormalize0 commented on client/src/views/NewPostView.vue
> +      <draggable v-model="slidesarray[current_image]"  handle=".handle" @dragstart="drag_start_handler">
Я сделал точно так же как в этом примере
https://sortablejs.github.io/Vue.Draggable/#/handle

2024-04-20 17:29 UTC, serynabatov commented on client/public/css/NewPostStyle.css
> +    font-size: 1.2em;
Ну по документации он его буквально в примерах применяет, это просто класс, который он так назвал, это не внутренний класс (ты его все еще не применяешь), нужно применить как у него в документации

`<vueper-slides
  ref="vueperslides2"
  :slide-ratio="1 / 8"
  :dragging-distance="50"
  @slide="$refs.vueperslides1 && $refs.vueperslides1.goToSlide($event.currentSlide.index, { emit: false })"
  :visible-slides="3"
  fixed-height="100px">
  <vueper-slide
    v-for="i in 8"
    :key="i"
    @click.native="$refs.vueperslides2 && $refs.vueperslides2.goToSlide(i - 1)">
    <template #content>
      <div class="vueperslide__content-wrapper" :style="'background-color: ' + ['#ff5252', '#42b983'][i % 2]">
        <div class="vueperslide__title">{{ i.toString() }}</div>
      </div>
    </template>
  </vueper-slide>
</vueper-slides>
`

2024-04-20 17:32 UTC, abnormalize0 commented on client/public/css/NewPostStyle.css
> +    font-size: 1.2em;
В этом примере он его применяет
https://antoniandre.github.io/vueper-slides/#ex--slide-image-inside
Ну и я вижу что я меняю этот стиль и подпись к изображениям меняется визуально

2024-04-20 18:03 UTC, serynabatov commented on client/public/css/NewPostStyle.css
> +    font-size: 1.2em;
Ну ладно оставь так 
Но это странно, обычно за переопределением класса требуется сделать преселекторы
Которых у тебя нет

2024-04-23 20:15 UTC, abnormalize0 commented on client/src/views/NewPostView.vue
> +        current_image: -1,
scale не используется прямо сейчас, я его оставил как задел на будущие фичи
last_id, да, костыль

2024-04-24 07:00 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        current_image: -1,
@abnormalize0 удали тогда пожалуйста неиспользуемые переменные
Чтобы я при превращении этого компонента в рабочий не задумывался о том как это должно работать)

2024-04-27 13:31 UTC, abnormalize0 commented on client/src/views/NewPostView.vue
> +          setTimeout(function() { that.recursive_shutdown() }, 50);
Заменил все таймауты конструкцией setTimeout(() => ...

2024-04-29 10:20 UTC, abnormalize0 commented
Вроде учел все замечания, @serynabatov ожидаю ревью

2024-04-29 19:01 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +      recursive_shutdown() {
См. коммент про рекурсию

2024-04-29 19:02 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +<style>
Перенеси <style></style> выше чем <script></script>, чтобы был один и тот же стиль

2024-04-29 19:02 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +    /* top: 40px; left: 40px; */
Удали комментарии

2024-04-30 09:01 UTC, abnormalize0 commented on client/src/views/NewPostView.vue
> +          { title: 'Текстовое поле', type: 'text' },
Потому что в новом документе сразу будет один блок. Не текстовый правда, а заголовок, но это я потом поменяю, когда у меня заголовки появятся.

2024-04-30 09:01 UTC, abnormalize0 commented on client/src/views/NewPostView.vue
> +          {name:'Element 0', id: 0, type: "text", insert_buttons: false, height: 0},
Потому что в новом документе сразу будет один блок. Не текстовый правда, а заголовок, но это я потом поменяю, когда у меня заголовки появятся.

2024-04-30 09:05 UTC, abnormalize0 commented on client/src/views/NewPostView.vue
> +        e.dataTransfer.setDragImage(new Image(), 0, 0);
Это модификация чтоб когда ты тянешь элемент то не было силуэта
https://stackoverflow.com/questions/62467390/styling-vuedraggle-elements

2024-04-30 09:50 UTC, abnormalize0 commented on client/src/views/NewPostView.vue
> +        setTimeout(() => this.block_element[target].classList.toggle("blink"), 300);
Тут логика такая, проскролить до нужного элемента а потом подсветить его. Если делать это без таймаута, то пока документ скроллится до нужного элемента подсветка уже закончится. И без задержки класс сразу 2 раза переключится, поэтому задержка внутри стиля не сработает как надо

2024-04-30 09:54 UTC, abnormalize0 commented on client/src/views/NewPostView.vue
> +          this.recursive_shutdown()
Смотри зачем использую. Во время скролла у меня появляется некий элемент, который через несколько секунд опять пропадает. НО, если пока он на экране я снова проскролю то таймер для него должен сброситься. Другими словами мне нужно чтоб пока пользователь скролит этот элемент оставался на экране, и пропадал спустя какое-то время когда пользователь перестал скроллить.

2024-04-30 09:57 UTC, abnormalize0 commented on client/src/views/NewPostView.vue
> +        this.scroll_position = this.worksheet.scrollTop * this.scale
В template оно неправильно работает, объект меняет свою позицию не мгновенно.

2024-04-30 10:00 UTC, abnormalize0 commented on client/src/views/NewPostView.vue
> +      this.scroll_height = this.worksheet.clientHeight * this.scale
Тут окей, это сработает

2024-04-30 10:01 UTC, abnormalize0 commented on client/src/views/NewPostView.vue
> +        block.height = this.block_element[cc].clientHeight * this.scale
В?

2024-04-30 10:03 UTC, abnormalize0 commented on client/src/views/NewPostView.vue
> +        this.blocks.splice(this.blocks.map(function (img) { return img.id; }).indexOf(target_block) + this.block_place, 0, {name:'Element ' + this.last_id, id: this.last_id, type: type, insert_button
С помощью splice вставляю элемент посреди массива, с помощью map нахожу куда его нужно вставить (у меня на входе есть айдишник блока перед или после которым надо вставить новый элемент, но все элементы в массиве вразброс лежат)

2024-04-30 10:04 UTC, abnormalize0 commented on client/src/views/NewPostView.vue
> +        this.blocks.splice(this.blocks.map(function (img) { return img.id; }).indexOf(target_block) + this.block_place, 0, {name:'Element ' + this.last_id, id: this.last_id, type: type, insert_button
Ну и {name:'Element ' и далее это то что я вставляю

2024-04-30 10:14 UTC, abnormalize0 commented on client/src/views/NewPostView.vue
> +        this.blocks.splice(this.blocks.map(function (img) { return img.id; }).indexOf(target_block) + this.block_place, 0, {name:'Element ' + this.last_id, id: this.last_id, type: type, insert_button
Заменил map на findIndex, стало чуть покороче
`this.blocks.splice(this.blocks.findIndex((element) => element.id == target_block) + this.block_place, 0, {name:'Element ' + this.last_id, id: this.last_id, type: type, insert_buttons:false, height: 0})`

2024-04-30 10:26 UTC, abnormalize0 commented on client/src/views/NewPostView.vue
> +        current_image: -1,
оставил для всех переменных комментарии, продублирую их сюда
```
scroll_position: 0,
scroll_fade: false,
scroll_visibility: false,   //три переменные которые отвечают за позиционирование и видимость указателя позиции в правом меню
image_src: "",              //переменная поля ввода адреса для вставки картинки
snackbar: false,            //видимость окна уведомления о том что нельзя удалять последнюю картинку
dialog: false,              //видимость окна добавления картинок
last_id: 1,                 //текущий последний идентификатор чтоб знать какой присваивать новым блокам
scale: 0.5,                 //множитель скалирования миниатюр в правом меню
timer: 0,                   //хехе рекурсия делает бррр
current_image: -1,          //идентификатор чтоб окну добавления картинок знать с каким элментом он работает
block_place: 0,             //добавлять новый блок до или после целевого
allow_menu: 1,              //позволять или нет поялвяться кнопкам при наведении на миниатюру (запрещаю если прямо сейчас происходить драгндроп)
markdown_content: [],       //содержимое текстовых полей маркдаун эдиторов
```

2024-04-30 20:20 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        block.height = this.block_element[cc].clientHeight * this.scale
Что такое B?
Я не понял .-.

2024-04-30 20:25 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        this.blocks.splice(this.blocks.map(function (img) { return img.id; }).indexOf(target_block) + this.block_place, 0, {name:'Element ' + this.last_id, id: this.last_id, type: type, insert_button
Давай с findIndex, так действительно понятнее

2024-04-30 20:27 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        e.dataTransfer.setDragImage(new Image(), 0, 0);
Ок, прочел 
Вопросы все еще остались, но к создателю ответа больше, оставим пока как у тебя

2024-04-30 20:28 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        setTimeout(() => this.block_element[target].classList.toggle("blink"), 300);
А почему подсветить нельзя сделать стандартными анимациями CSS?

2024-04-30 20:29 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        this.scroll_position = this.worksheet.scrollTop * this.scale
А можешь показать код при котором такое происходит с template? 
Если в нем нет ошибки, то оставим пока так

2024-04-30 20:33 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +          this.recursive_shutdown()
Ну из того что ты написал, достаточно сделать отдельный  виджет, которому будет в props передаваться информация о том что ему нужно удалиться или нет 

Я пока не понял почему все еще рекурсия и ты не можешь решить это итеративным способом

Здесь вопрос чисто технический встает, потому что в случае рекурсии, переполнится стек функций в джаваскрипте, который туда сует все что не попадя

Из-за этого кстати надо и думать, что делать с setTimeout, потому что это не таймауты в С++, они не гарантируют тебе того, что условно через 2 секунды появится то, что требуется
Они гарантируют как минимум через 2 секунды, возможно и дольше 

Таким образом сами сет таймауты вносят в наш сайт non-determenistic поведение
А тут еще и рекурсия подключена

2024-05-01 10:20 UTC, abnormalize0 commented on client/src/views/NewPostView.vue
> +        block.height = this.block_element[cc].clientHeight * this.scale
Я тоже. Где изменения высоты должны находиться? В template?
![image](https://github.com/abnormalize0/DailyTeleFrog/assets/61551851/0f4524ce-e444-4e8e-901c-38f7f46b5415)

2024-05-01 10:48 UTC, abnormalize0 commented on client/src/views/NewPostView.vue
> +          this.recursive_shutdown()
> Я пока не понял почему все еще рекурсия и ты не можешь решить это итеративным способом
Потому что сеттаймауты в лупах просто не работают
А то что это будут +- 2 секунды это не страшно, мне нужно чтоб оно просто "на какое-то" время подсветилось, а будут это 2 секунды или 4 разницы особо нет на самом деле

2024-05-01 10:50 UTC, abnormalize0 commented on client/src/views/NewPostView.vue
> +        this.scroll_position = this.worksheet.scrollTop * this.scale
`:style="{ top: worksheet.scrollTop * scale + 'px', }`
вот так оно не работает

2024-05-01 10:58 UTC, abnormalize0 commented on client/src/views/NewPostView.vue
> +        setTimeout(() => this.block_element[target].classList.toggle("blink"), 300);
Потому что через жс я не могу по желанию включить ту или иную анимацию, я могу только toggle class, поэтому у меня есть класс .blink с белым фоном который я по таймауту включаю а потом по таймауту выключаю

2024-05-01 16:50 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        block.height = this.block_element[cc].clientHeight * this.scale
Да, или сделай его в mounted() 
А не в updated() 
Потому что в updated оно будет бесконечно вызываться, и у тебя стек переполнится 
А в mounted только при монтировании компонента

2024-05-01 17:18 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +          this.recursive_shutdown()
Там проблема не в том что оно 4 секунды отработает 
А почему в лупах не отработают? 
Давай созвонимся, посмотрим

2024-05-01 18:21 UTC, serynabatov commented on client/src/views/NewPostView.vue
> +        setTimeout(() => this.block_element[target].classList.toggle("blink"), 300);
https://codepen.io/brody/pen/XNgYNW

2024-05-04 14:13 UTC, abnormalize0 commented
Пока что непонятно что делать со `scroll_position` и как вытащить `block.height` из `updated`. Кроме этого все замечания были учтены так что мержу.

2024-05-04 14:13 UTC, merged